<?php
/**
* 2007-2017 PrestaShop
*
* Jms Mega Menu module for prestashop
*
*  @author    Joommasters <joommasters@gmail.com>
*  @copyright 2007-2017 Joommasters
*  @license   license http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL
*  @Website: http://www.joommasters.com
*/

$query = "DROP TABLE IF EXISTS `_DB_PREFIX_jmsmegamenu`;
CREATE TABLE IF NOT EXISTS `_DB_PREFIX_jmsmegamenu` (
  `mitem_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `id_shop` int(11) unsigned NOT NULL,
  `parent_id` int(10) unsigned NOT NULL,
  `type` varchar(30) NOT NULL,
  `value` varchar(255) NOT NULL,
  `html_content` text NOT NULL,
  `active` tinyint(1) NOT NULL,
  `target` varchar(25) NOT NULL,
  `params` text NOT NULL,
  `ordering` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`mitem_id`)
) ENGINE=_MYSQL_ENGINE_  DEFAULT CHARSET=utf8 AUTO_INCREMENT=111 ;

INSERT INTO `_DB_PREFIX_jmsmegamenu` (`mitem_id`, `id_shop`, `parent_id`, `type`, `value`, `html_content`, `active`, `target`, `params`, `ordering`) VALUES
(1, 1, 0, 'link', '#', '', 1, '_self', '{\"align\":\"left\",\"sub\":{\"row\":[[{\"width\":\"12\",\"items\":[{\"item\":\"8\"},{\"item\":\"9\"},{\"item\":\"10\"},{\"item\":\"11\"}]}]]}}', 0),
(2, 1, 0, 'link', '#', '', 1, '_self', '{\"class\":\"megamenu-custom\",\"sub\":{\"fullwidth\":\"1\",\"row\":[[{\"width\":\"2\",\"class\":\"change-width\",\"items\":[{\"item\":\"90\"},{\"item\":\"109\"},{\"item\":\"91\"},{\"item\":\"92\"},{\"item\":\"93\"},{\"item\":\"95\"}]},{\"width\":\"2\",\"class\":\"change-width\",\"items\":[{\"item\":\"96\"},{\"item\":\"97\"},{\"item\":\"98\"},{\"item\":\"99\"},{\"item\":\"100\"},{\"item\":\"101\"}]},{\"width\":\"3\",\"class\":\"change-width last\",\"items\":[{\"item\":\"102\"},{\"item\":\"103\"},{\"item\":\"104\"},{\"item\":\"105\"},{\"item\":\"106\"},{\"item\":\"107\"}]},{\"width\":\"5\",\"class\":\"image-column\",\"items\":[{\"item\":\"108\"}]}]]}}', 1),
(4, 1, 0, 'link', '#', '', 1, '_self', '{}', 2),
(5, 1, 0, 'link', '#', '', 1, '_self', '{\"sub\":{\"row\":[[{\"width\":\"12\",\"items\":[{\"item\":\"77\"},{\"item\":\"78\"},{\"item\":\"79\"},{\"item\":\"80\"}]}]]}}', 5),
(6, 1, 0, 'link', '#', '', 1, '_self', '{\"sub\":{\"row\":[[{\"width\":\"12\",\"items\":[{\"item\":\"81\"},{\"item\":\"83\"},{\"item\":\"86\"},{\"item\":\"87\"},{\"item\":\"89\"}]}]]}}', 4),
(7, 1, 0, 'link', 'index.php?controller=contact', '', 1, '_self', '{}', 6),
(8, 1, 1, 'link', 'index.php?settingpanel=1&jpb_homepage=1', '', 1, '_self', '{\"title\":\"1\"}', 1),
(9, 1, 1, 'link', 'index.php?settingpanel=1&jpb_homepage=2', '', 1, '_self', '{\"title\":\"1\"}', 2),
(10, 1, 1, 'link', 'index.php?settingpanel=1&jpb_homepage=3', '<div class=\"img-menu\"><img src=\"themes/jms_onebuy/img/demo/megamenu/megamenu_img03.jpg\" alt=\"Mega Menu Img\" /></div>', 1, '_self', '{\"title\":\"1\"}', 3),
(77, 1, 5, 'jmsblog-category', '1', '', 1, '_self', '{\"title\":\"1\"}', 1),
(78, 1, 5, 'jmsblog-categories', 'jmsblog_categories', '', 1, '_self', '{\"title\":\"1\"}', 2),
(79, 1, 5, 'jmsblog-archive', '2015-10', '', 1, '_self', '{\"title\":\"1\"}', 3),
(80, 1, 5, 'jmsblog-tag', 'fashion', '', 1, '_self', '{\"title\":\"1\"}', 4),
(81, 1, 6, 'cms', '4', '', 1, '_self', '{\"title\":\"1\"}', 1),
(83, 1, 6, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 2),
(84, 1, 83, 'category', '3', '', 1, '_self', '', 1),
(85, 1, 83, 'product', '18', '', 1, '_self', '', 3),
(86, 1, 6, 'link', 'index.php?fc=module&module=blockwishlist&controller=mywishlist', '', 1, '_self', '{\"title\":\"1\"}', 4),
(87, 1, 6, 'link', 'index.php?controller=products-comparison', '', 1, '_self', '{\"title\":\"1\"}', 5),
(89, 1, 6, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 6),
(90, 1, 2, 'category', '116', '', 1, '_self', '{\"title\":\"1\",\"group\":\"1\"}', 0),
(91, 1, 2, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 1),
(92, 1, 2, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 3),
(93, 1, 2, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 4),
(95, 1, 2, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 5),
(96, 1, 2, 'category', '112', '', 1, '_self', '{\"title\":\"1\",\"group\":\"1\"}', 6),
(97, 1, 2, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 7),
(98, 1, 2, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 8),
(99, 1, 2, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 9),
(100, 1, 2, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 10),
(101, 1, 2, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 11),
(102, 1, 2, 'link', '#', '', 1, '_self', '{\"title\":\"1\",\"group\":\"1\"}', 12),
(103, 1, 2, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 13),
(104, 1, 2, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 14),
(105, 1, 2, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 15),
(106, 1, 2, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 16),
(107, 1, 2, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 17),
(108, 1, 2, 'html', 'html_content', '<div class=\"image-menu\"><a href=\"#\"> <img src=\"themes/jms_bread/assets/img/demo/image_menu.jpg\" alt=\"Menu Image\" /></a>\r\n<div class=\"flex-wrapper\">\r\n<div class=\"flex-box\">\r\n<div class=\"small-text\">UP TO 50% OFF</div>\r\n<div class=\"large-text\">NEW ARRIVAL</div>\r\n</div>\r\n</div>\r\n</div>', 1, '_self', '{\"title\":\"0\"}', 18),
(109, 1, 2, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 2),
(110, 1, 0, 'link', '#', '', 1, '_self', '', 3);

DROP TABLE IF EXISTS `_DB_PREFIX_jmsmegamenu_lang`;
CREATE TABLE IF NOT EXISTS `_DB_PREFIX_jmsmegamenu_lang` (
  `mitem_id` int(11) NOT NULL,
  `id_lang` int(11) NOT NULL,
  `name` varchar(50) NOT NULL,
  `description` text NOT NULL
) ENGINE=_MYSQL_ENGINE_ DEFAULT CHARSET=utf8;

INSERT INTO `_DB_PREFIX_jmsmegamenu_lang` (`mitem_id`, `id_lang`, `name`, `description`) VALUES
(1, 1, 'Home', ''),
(1, 7, 'Home', ''),
(2, 1, 'Categories', ''),
(2, 7, 'Store', ''),
(4, 1, 'Stores', ''),
(4, 7, 'Brands', ''),
(5, 1, 'Blog', ''),
(5, 7, 'Blog', ''),
(6, 1, 'Pages', ''),
(6, 7, 'Pages', ''),
(7, 1, 'Contact', ''),
(7, 7, 'Contact', ''),
(8, 1, 'Home 1', ''),
(8, 7, 'Home 1', ''),
(9, 1, 'Home 2', ''),
(9, 7, 'Home 2', ''),
(10, 1, 'Home 3', ''),
(10, 7, 'Home 3', ''),
(77, 1, 'Blog Category', ''),
(77, 7, 'Blog Category', ''),
(78, 1, 'Blog Categories', ''),
(78, 7, 'Blog Categories', ''),
(79, 1, 'Blog Archives', ''),
(79, 7, 'Blog Archives', ''),
(80, 1, 'Blog Tags', ''),
(80, 7, 'Blog Tags', ''),
(81, 1, 'About Us', ''),
(81, 7, 'About Us', ''),
(83, 1, 'Product Pages', ''),
(83, 7, 'Product Pages', ''),
(84, 1, 'Product List', ''),
(84, 7, 'Product List', ''),
(85, 1, 'Product Details', ''),
(85, 7, 'Product Details', ''),
(86, 1, 'Wishlist Page', ''),
(86, 7, 'Search Page', ''),
(87, 1, 'Compare Page', ''),
(87, 7, 'Compare Page', ''),
(89, 1, '404 Page', ''),
(89, 7, '404 Page', ''),
(90, 1, 'Wedding Cake', ''),
(90, 7, 'Wedding Cake', ''),
(91, 1, 'Cream Cake', ''),
(91, 7, 'Cream Cake', ''),
(92, 1, 'Fruit Desserts', ''),
(92, 7, 'Fruit Desserts', ''),
(93, 1, 'Celebration Cake', ''),
(93, 7, 'Celebration Cake', ''),
(95, 1, 'Chicken Cake', ''),
(95, 7, 'Chicken Cake', ''),
(96, 1, 'Birthday Cake', ''),
(96, 7, 'Birthday Cake', ''),
(97, 1, 'Cakes for Father', ''),
(97, 7, 'Cakes of Father', ''),
(98, 1, 'Cakes for Mother', ''),
(98, 7, 'Cakes for Mother', ''),
(99, 1, 'Cakes for Kid', ''),
(99, 7, 'Cakes for Kid', ''),
(100, 1, 'Cake for Lover', ''),
(100, 7, 'Cake for Lover', ''),
(101, 1, 'Customer Design', ''),
(101, 7, 'Customer Design', ''),
(102, 1, 'Awesome Cakes', ''),
(102, 7, 'Awesome Cakes', ''),
(103, 1, 'White Cream', ''),
(103, 7, 'White Cream', ''),
(104, 1, 'Ice Cream Cakes', ''),
(104, 7, 'Ice Cream Cakes', ''),
(105, 1, 'Fruit Cakes', ''),
(105, 7, 'Fruit Cakes', ''),
(106, 1, 'Eggs Cake', ''),
(106, 7, 'Eggs Cake', ''),
(107, 1, 'Our Special', ''),
(107, 7, 'Our Special', ''),
(108, 1, 'Image Menu', ''),
(108, 7, 'Image Menu', ''),
(109, 1, 'Sweet Cakes', ''),
(109, 7, 'Sweet Cakes', ''),
(110, 1, 'Services', ''),
(110, 7, 'Services', ''),
(1, 2, 'Home', ''),
(2, 2, 'Categories', ''),
(4, 2, 'Stores', ''),
(5, 2, 'Blog', ''),
(6, 2, 'Pages', ''),
(7, 2, 'Contact', ''),
(8, 2, 'Home 1', ''),
(9, 2, 'Home 2', ''),
(10, 2, 'Home 3', ''),
(77, 2, 'Blog Category', ''),
(78, 2, 'Blog Categories', ''),
(79, 2, 'Blog Archives', ''),
(80, 2, 'Blog Tags', ''),
(81, 2, 'About Us', ''),
(83, 2, 'Product Pages', ''),
(84, 2, 'Product List', ''),
(85, 2, 'Product Details', ''),
(86, 2, 'Wishlist Page', ''),
(87, 2, 'Compare Page', ''),
(89, 2, '404 Page', ''),
(90, 2, 'Wedding Cake', ''),
(91, 2, 'Cream Cake', ''),
(92, 2, 'Fruit Desserts', ''),
(93, 2, 'Celebration Cake', ''),
(95, 2, 'Chicken Cake', ''),
(96, 2, 'Birthday Cake', ''),
(97, 2, 'Cakes for Father', ''),
(98, 2, 'Cakes for Mother', ''),
(99, 2, 'Cakes for Kid', ''),
(100, 2, 'Cake for Lover', ''),
(101, 2, 'Customer Design', ''),
(102, 2, 'Awesome Cakes', ''),
(103, 2, 'White Cream', ''),
(104, 2, 'Ice Cream Cakes', ''),
(105, 2, 'Fruit Cakes', ''),
(106, 2, 'Eggs Cake', ''),
(107, 2, 'Our Special', ''),
(108, 2, 'Image Menu', ''),
(109, 2, 'Sweet Cakes', ''),
(110, 2, 'Services', ''),
(1, 3, 'Home', ''),
(2, 3, 'Categories', ''),
(4, 3, 'Stores', ''),
(5, 3, 'Blog', ''),
(6, 3, 'Pages', ''),
(7, 3, 'Contact', ''),
(8, 3, 'Home 1', ''),
(9, 3, 'Home 2', ''),
(10, 3, 'Home 3', ''),
(77, 3, 'Blog Category', ''),
(78, 3, 'Blog Categories', ''),
(79, 3, 'Blog Archives', ''),
(80, 3, 'Blog Tags', ''),
(81, 3, 'About Us', ''),
(83, 3, 'Product Pages', ''),
(84, 3, 'Product List', ''),
(85, 3, 'Product Details', ''),
(86, 3, 'Wishlist Page', ''),
(87, 3, 'Compare Page', ''),
(89, 3, '404 Page', ''),
(90, 3, 'Wedding Cake', ''),
(91, 3, 'Cream Cake', ''),
(92, 3, 'Fruit Desserts', ''),
(93, 3, 'Celebration Cake', ''),
(95, 3, 'Chicken Cake', ''),
(96, 3, 'Birthday Cake', ''),
(97, 3, 'Cakes for Father', ''),
(98, 3, 'Cakes for Mother', ''),
(99, 3, 'Cakes for Kid', ''),
(100, 3, 'Cake for Lover', ''),
(101, 3, 'Customer Design', ''),
(102, 3, 'Awesome Cakes', ''),
(103, 3, 'White Cream', ''),
(104, 3, 'Ice Cream Cakes', ''),
(105, 3, 'Fruit Cakes', ''),
(106, 3, 'Eggs Cake', ''),
(107, 3, 'Our Special', ''),
(108, 3, 'Image Menu', ''),
(109, 3, 'Sweet Cakes', ''),
(110, 3, 'Services', ''),
(1, 4, 'Home', ''),
(2, 4, 'Categories', ''),
(4, 4, 'Stores', ''),
(5, 4, 'Blog', ''),
(6, 4, 'Pages', ''),
(7, 4, 'Contact', ''),
(8, 4, 'Home 1', ''),
(9, 4, 'Home 2', ''),
(10, 4, 'Home 3', ''),
(77, 4, 'Blog Category', ''),
(78, 4, 'Blog Categories', ''),
(79, 4, 'Blog Archives', ''),
(80, 4, 'Blog Tags', ''),
(81, 4, 'About Us', ''),
(83, 4, 'Product Pages', ''),
(84, 4, 'Product List', ''),
(85, 4, 'Product Details', ''),
(86, 4, 'Wishlist Page', ''),
(87, 4, 'Compare Page', ''),
(89, 4, '404 Page', ''),
(90, 4, 'Wedding Cake', ''),
(91, 4, 'Cream Cake', ''),
(92, 4, 'Fruit Desserts', ''),
(93, 4, 'Celebration Cake', ''),
(95, 4, 'Chicken Cake', ''),
(96, 4, 'Birthday Cake', ''),
(97, 4, 'Cakes for Father', ''),
(98, 4, 'Cakes for Mother', ''),
(99, 4, 'Cakes for Kid', ''),
(100, 4, 'Cake for Lover', ''),
(101, 4, 'Customer Design', ''),
(102, 4, 'Awesome Cakes', ''),
(103, 4, 'White Cream', ''),
(104, 4, 'Ice Cream Cakes', ''),
(105, 4, 'Fruit Cakes', ''),
(106, 4, 'Eggs Cake', ''),
(107, 4, 'Our Special', ''),
(108, 4, 'Image Menu', ''),
(109, 4, 'Sweet Cakes', ''),
(110, 4, 'Services', ''),
(1, 5, 'Home', ''),
(2, 5, 'Categories', ''),
(4, 5, 'Stores', ''),
(5, 5, 'Blog', ''),
(6, 5, 'Pages', ''),
(7, 5, 'Contact', ''),
(8, 5, 'Home 1', ''),
(9, 5, 'Home 2', ''),
(10, 5, 'Home 3', ''),
(77, 5, 'Blog Category', ''),
(78, 5, 'Blog Categories', ''),
(79, 5, 'Blog Archives', ''),
(80, 5, 'Blog Tags', ''),
(81, 5, 'About Us', ''),
(83, 5, 'Product Pages', ''),
(84, 5, 'Product List', ''),
(85, 5, 'Product Details', ''),
(86, 5, 'Wishlist Page', ''),
(87, 5, 'Compare Page', ''),
(89, 5, '404 Page', ''),
(90, 5, 'Wedding Cake', ''),
(91, 5, 'Cream Cake', ''),
(92, 5, 'Fruit Desserts', ''),
(93, 5, 'Celebration Cake', ''),
(95, 5, 'Chicken Cake', ''),
(96, 5, 'Birthday Cake', ''),
(97, 5, 'Cakes for Father', ''),
(98, 5, 'Cakes for Mother', ''),
(99, 5, 'Cakes for Kid', ''),
(100, 5, 'Cake for Lover', ''),
(101, 5, 'Customer Design', ''),
(102, 5, 'Awesome Cakes', ''),
(103, 5, 'White Cream', ''),
(104, 5, 'Ice Cream Cakes', ''),
(105, 5, 'Fruit Cakes', ''),
(106, 5, 'Eggs Cake', ''),
(107, 5, 'Our Special', ''),
(108, 5, 'Image Menu', ''),
(109, 5, 'Sweet Cakes', ''),
(110, 5, 'Services', ''),
(1, 6, 'Home', ''),
(2, 6, 'Categories', ''),
(4, 6, 'Stores', ''),
(5, 6, 'Blog', ''),
(6, 6, 'Pages', ''),
(7, 6, 'Contact', ''),
(8, 6, 'Home 1', ''),
(9, 6, 'Home 2', ''),
(10, 6, 'Home 3', ''),
(77, 6, 'Blog Category', ''),
(78, 6, 'Blog Categories', ''),
(79, 6, 'Blog Archives', ''),
(80, 6, 'Blog Tags', ''),
(81, 6, 'About Us', ''),
(83, 6, 'Product Pages', ''),
(84, 6, 'Product List', ''),
(85, 6, 'Product Details', ''),
(86, 6, 'Wishlist Page', ''),
(87, 6, 'Compare Page', ''),
(89, 6, '404 Page', ''),
(90, 6, 'Wedding Cake', ''),
(91, 6, 'Cream Cake', ''),
(92, 6, 'Fruit Desserts', ''),
(93, 6, 'Celebration Cake', ''),
(95, 6, 'Chicken Cake', ''),
(96, 6, 'Birthday Cake', ''),
(97, 6, 'Cakes for Father', ''),
(98, 6, 'Cakes for Mother', ''),
(99, 6, 'Cakes for Kid', ''),
(100, 6, 'Cake for Lover', ''),
(101, 6, 'Customer Design', ''),
(102, 6, 'Awesome Cakes', ''),
(103, 6, 'White Cream', ''),
(104, 6, 'Ice Cream Cakes', ''),
(105, 6, 'Fruit Cakes', ''),
(106, 6, 'Eggs Cake', ''),
(107, 6, 'Our Special', ''),
(108, 6, 'Image Menu', ''),
(109, 6, 'Sweet Cakes', ''),
(110, 6, 'Services', '');
";
